# Generated by Django 3.2 on 2023-03-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('spe', 'Special'), ('reg', 'Regular'), ('vip', 'VIP')], default='VIP', max_length=80)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Appartment Categories',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
                ('passenger_capacity', models.IntegerField()),
                ('laggage', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_type', models.CharField(choices=[('p', 'Petro'), ('d', 'Diesel')], default='Petro', max_length=20)),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=9)),
                ('late_fee_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Car Categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='Media/Services/Service-Thumbnails')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(max_length=15)),
                ('model_name', models.CharField(max_length=50)),
                ('model_year', models.IntegerField()),
                ('transmission', models.CharField(choices=[('man', 'Manual'), ('auto', 'Automatic')], max_length=15)),
                ('availability', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='services/uploads')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='services/uploads')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='services.category')),
            ],
            options={
                'ordering': ('-registered_at',),
            },
        ),
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appartment_name', models.CharField(max_length=200)),
                ('bed_type', models.CharField(choices=[('sin', 'Single'), ('dou', 'Double'), ('que', 'Queen'), ('kin', 'King')], default='Single', max_length=20)),
                ('appartment_capacity', models.IntegerField()),
                ('cost_per_night', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='Services/appartments-thumbnails/')),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='Services/appartments-thumbnails/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='Services/appartments-thumbnails/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='Services/appartments-thumbnails/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('availability', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('available', 'Available')], default='Available', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='services.apartmentcategory')),
            ],
        ),
    ]
