# Generated by Django 3.2 on 2023-03-23 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('gov_id', models.CharField(max_length=18)),
                ('phone_number', models.CharField(max_length=18)),
                ('checkin_date', models.CharField(blank=True, max_length=18)),
                ('checkout_date', models.CharField(blank=True, max_length=18)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.appartment')),
            ],
            options={
                'ordering': ('-booked_at',),
            },
        ),
        migrations.CreateModel(
            name='CarHiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('driving_licence_no', models.CharField(max_length=18)),
                ('phone_number', models.CharField(max_length=18)),
                ('pickup_location', models.CharField(max_length=200)),
                ('pickup_date', models.CharField(blank=True, max_length=18)),
                ('dropoff_date', models.CharField(blank=True, max_length=18)),
                ('pickup_time', models.TimeField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.car')),
            ],
            options={
                'ordering': ('-booked_at',),
            },
        ),
    ]
